version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      OPENAI_API_KEY: OPENAI_API_KEY
      OPENAI_MODEL: "gpt-4o-mini"
      CORS_ORIGIN: "http://localhost:3000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_BASE_URL: "http://localhost:3001"
    depends_on:
      - backend
    restart: unless-stopped


